### ISSUE TITLE
edit spreading event, perhaps

### ISSUE THREAD

**Issue by nebogeo** [fo-am/crapapppro#41]

**Comment by nebogeo** [comment]
This is actually by design, as I think it leads to ambiguous situations if it's made editable. 

For example the event pulls in the all the field information and stores it, as fields can be changed over time, as new crops are grown etc. If the event was made editable then we'd need to decide if it should update to the current field conditions - or whether changes in the event need to be reflected in the field. 

I think they work better, and it's clearer as a record of dated snapshots of the field conditions/situation, which can be deleted as required.

**Comment by beckyduchy** [comment]
Ok, that sounds fine, thanks.

Whether we just need to make it clear to users that if they are adding their spreading event and they make a mistake, how to get rid of it.

Thanks
\becky
